### ISSUE TITLE
[Bug] sp_Doc: </details> present even with no object in section

### ISSUE THREAD

**Issue by PierreLetter** [LowlyDBA/ExpressSQL#122]
**Describe the bug**
When there is no object in a section (views for example), the section is not present thanks to the first check:
IF EXISTS (SELECT 1 FROM [sys].[views] WHERE [is_ms_shipped] = 0)
However, the closing </details> is there beause there is no check

**To Reproduce**
Run sp_doc on a database with no views, or no procedures

**Expected behavior**
Either the 'Begin ... End' statement should be for the whole section, or there should be another check for the 'End collapsible view section' part

**Versions(please complete the following information):**

* OS: Windows
* SQL Server: 2019
* SSMS: 18.6

**Additional context**
If you tell me if you prefer Being ... End (my favored solution) or add another IF at the end of the section, I can do a PR.

**Comment by LowlyDBA** [comment]
Thank you!

I agree that a begin/end covering the whole thing seems like a good
approach.

**Comment by LowlyDBA** [comment]
@PierreLetter I'm just going to wrap this fix into #123 since its sort of a bad bug. Thank you for volunteering to do a PR on it though!
