### ISSUE TITLE
[obj_name] column is too short to contain the results

### ISSUE THREAD

**Issue by runamuk0** [LowlyDBA/ExpressSQL#97]
When I execute the **sp_sizeoptimiser** stored procedure against my database I get the following error message:
```
...
Check 15 - Inefficient indexes
Msg 50000, Level 16, State 30, Procedure dbo.sp_sizeoptimiser, Line 1209 [Batch Start Line 1245]
String or binary data would be truncated.
```

Debugging the code I found that the [obj_name] columns were using sysname.  I increased the size of the [obj_name] columns to NVARCHAR(1024) and it fixed the problem.

**Comment by LowlyDBA** [comment]
Thanks for opening an issue!

Could you also try with `NVARCHAR(400)`? 

It looks like the that column needs to be able to hold schema name + obj name + index name which would be 384 chars (128 * 3) in addition to to formatting characters, which we can round up to 400.

**Comment by runamuk0** [comment]
`NVARCHAR(400)` worked as well.

**Comment by LowlyDBA** [comment]
Thanks @runamuk0!

**Comment by runamuk0** [comment]
Please be sure to fix it in the following places as well:
`CREATE TABLE #DuplicateIndex
...`

`CREATE TABLE #OverlappingIndex
...`
